### ISSUE TITLE
This is cool. Windows report

### ISSUE THREAD

**Issue by shopglobal** [electrovault/electrovault-desktop#2]
Hey Dev, this is great, by the way I love electron. The flexibility within nodeJs and electron with c being native makes for a smooth application. Listen the VueJs templates are amazing, so clever. 

Just wanted to point out two things. The ``build:win32`` where build is stated as  successful for both main and router, when application is launched we are seeing a white screen. 
When I checked the app folder structure I can see that there is no "app" folder inside resources. In my experience with electron, there is an app folder there where your application is started by electron dlls, per machine it may differ. 

Secondly where as with ``` yarn dev ``` we are seeing the "Welcome" screen followed by successful "install" with the electroneum daemon running *(and cleverly console logged outputs, bravo). The issue on the ``` yarn dev ``` is that the application hangs up on the blockchain update, even though in the dev tools I can see that we are fully sync'd (we run a pool as well so I know our nodes are solid) 

 Noticed that the app can't yet recognize the electroneumd install directory or locate electroneumd to bypass install. We could do this with fs given the user a prompt to enter the location and then searching for electroneumd in the directory provided.  

Any assistance would be great, there are no errors or stack traces to show, so far so good. Must be some tweaking per windows or app folder structure I presume. 

Thanks in advance. Great app! Should be official Electroneum app if it does work.

**Comment by jakejimenez** [comment]
Just built the application using `build:win32` and everything seemed to be working fine. This may be due to the commits I pushed out just after your issue. Additionally, the app will be supporting downloaded directories of electroneumd in the future, but for now, downloading it ourselves allows everything to run more smoothly. 

Go ahead and give it a go now.

**Comment by shopglobal** [comment]
Trying master again

Thanks

**Comment by shopglobal** [comment]
Ok @r00t1000 on master during ``` yarn dev ```  I am still getting stuck at the ``` Downloading Blockchain (This could take a while) ```
However my node is fully synced. 

Same issue of the app showing white screen in ``` build:win32 ``` 
There is still no ``` resources/app ``` dir.  




``

**Comment by jakejimenez** [comment]
Are you sure you are running the correct command? The command for running it in dev is `yarn run dev`. as for the downloading blockchain bit, does it at least open `electroneumd.exe` in your Task Manager.

EDIT: Try running the built app as administrator. That seems to work for me. Also, the application is not yet working for OS X or Linux.

**Comment by shopglobal** [comment]
Yes after ```yarn run dev``` installation is successful and
electroneumd.exe is running. Also my node is synced (I can see console log
showing synced 100%)

However electrovault hangs up on blockchain sync step, and does not show
successful sync on app landing page, even though the blockchain is synced
and I can see in the app console log that we are synced 100%







On Jan 20, 2018 11:34 AM, "Anon" <notifications@github.com> wrote:

Are you sure you are running the correct command? The command for running
it in dev is yarn run dev. as for the downloading blockchain bit, does it
at least open electroneumd.exe in your Task Manager.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/electrovault/electrovault-desktop/issues/2#issuecomment-359183924>,
or mute the thread

**Comment by shopglobal** [comment]
Was there a solution?

On Jan 27, 2018 8:58 PM, "Anon" <notifications@github.com> wrote:

Closed #2 <https://github.com/electrovault/electrovault-desktop/issues/2>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/electrovault/electrovault-desktop/issues/2#event-1445036217>,
or mute the thread
